import javax.swing.JTextArea;

/**
 * Graphics screen for the Help menu
 * @author Osama Yousef
 * @author So Yoon Kim
 */
public class Help extends javax.swing.JFrame {

    /**
     * Creates new screen for help
     */
    public Help() {
        initComponents();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void initComponents() {

        text = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);
        //Adding Text Message
        String testStr = "How to add new buildings as admin\r\n"
        		+ "- Click the 'Add Map' button on the main page.\r\n"
        		+ "- Insert 'Building Name,' 'Building Image,' select the number of floors, and select a floor to add layers for each floor of the building.\r\n"
        		+ "- Click the 'Finish' button. \r\n"
        		+ "\r\n"
        		+ "How to choose maps \r\n"
        		+ "- Click a building image on the main page and click the 'View Building' button.\r\n"
        		+ "- It will show different colours on the floor layer when 'Accessibility Layer (green),' 'Washrooms (light pink),' 'Classrooms (orange),' 'Labs (yellow),' and 'Restaurants (dark pink)' are selected.\r\n"
        		+ "\r\n"
        		+ "How to choose floors\r\n"
        		+ "- Click a building image on the main page and click the 'View Building' button.\r\n"
        		+ "- Floor can be changed using the arrow up or arrow down button on the bottom right side.\r\n"
        		+ "\r\n"
        		+ "How to add POIs\r\n"
        		+ "- Click the 'Add POI' button on the 'View Building' page. \r\n"
        		+ "- Click on a map to pinpoint adding POIs when the 'Add POI' button colour changes to yellow. \r\n"
        		+ "- Description will be shown when the pinpoint is selected.";
        JTextArea wrapArea = new JTextArea(testStr, 1, 10);
        wrapArea.setLineWrap(true);
        wrapArea.setWrapStyleWord(true);
        wrapArea.setCaretPosition(testStr.length());
        wrapArea.setEditable(false);

        text.setText("THIS IS HELP");

        jButton1.setText("Close");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jButton1MousePressed(evt);
            }
        });

        int firstGap = 100;
        int secondGap = 275;

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(wrapArea, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(firstGap,firstGap,firstGap))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(secondGap, secondGap, secondGap))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(wrapArea, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
        setLocationRelativeTo(null);
    }

    /**
     * Function performed when the close button is pressed
     * @param evt Mouse event that triggers this function
     */
    private void jButton1MousePressed(java.awt.event.MouseEvent evt) {
        dispose();
    }

    /**
     * Method to run this class individually
     * Only would run for quick testing, no exterior functions available
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Help().setVisible(true);
            }
        });
    }

    // Variables declaration
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel text;
    // End of variables declaration
}
